### PR TITLE
gRPC Support

### PR DESCRIPTION
**Pull request by iamacarpet**
Hello @tomwalder ,

Here is the gRPC Support for the Second Generation runtime on App Engine.

Still waiting on the merge of the Datastore classes into `google-cloud-php`, so it references our own build for now.

Regards,
iamacarpet

### CODE REVIEW

**Comment by iamacarpet** [comment]
Looks like Travis is failing due to my `datastore-grpc` not being a stable dependency.

Will wait until it's released in `google-cloud-php` to fix, but we are running this in production and it is working, minus the composer issue installing it, if anyone is interested.

**Comment by tomwalder** [comment]
Thanks for this - I'd be keen to merge in when we know it's good to go.

Can you link to your PR for `google-cloud-php` ?

**Comment by iamacarpet** [comment]
Sure, it is one from Google themselves:

https://github.com/googleapis/google-cloud-php/pull/1429

Been open a while and still haven't been reviewed, even though they did it themselves.

**Comment by iamacarpet** [comment]
@tomwalder Google have released their changes for the official `google-cloud-php` library, so this is ready to go.

It has been deployed on our production app for a few hours and looks good so far.

**Comment by tomwalder** [comment]
@iamacarpet FYI - this branch is being merged and updated a little around the Firestore move from Google. Thanks again for your hard work so far!

**Pull request merged**
